name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "env DATABASE_URL=file:./dev.sqlite npx prisma generate"
dev = "env DATABASE_URL=file:./dev.sqlite npx prisma migrate deploy && env DATABASE_URL=file:./dev.sqlite npm exec react-router dev"
